config/routes.rb
<<<<<<< HEAD
Chefback::Application.routes.draw do
  resources :ingredients

  resources :inventories

  resources :foods

  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions" }
  resources :users

   root :to => 'registrations#new'

end
=======
Angelhack::Application.routes.draw do
  devise_for :users

end
>>>>>>> c56ea2630fc8ac933650255f399e6e1d074a01a2

app/models/food.rb
class Food < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :user
  has_many :ingredients
  attr_accessible :name, :price, :ingredients_attributes
  accepts_nested_attributes_for :ingredients
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @foods }
    end
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
    @food = Food.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @food }
    end
  end

  # GET /foods/new
  # GET /foods/new.json
  def new
    @food = Food.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @food }
    end
  end

  # GET /foods/1/edit
  def edit
    @food = Food.find(params[:id])
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(params[:food])

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render json: @food, status: :created, location: @food }
      else
        format.html { render action: "new" }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /foods/1
  # PUT /foods/1.json
  def update
    @food = Food.find(params[:id])

    respond_to do |format|
      if @food.update_attributes(params[:food])
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food = Food.find(params[:id])
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<%= form_for(@food) do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% @food.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="field">
    <%= f.label :Name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>
asdf
<%= f.fields_for :ingredients do |builder| %>

  <%= builder.label :ingredient_name, "name of ingredient " %><br/>asdf
  <%= builder.text_area :ingredient_name %>asdf

<% end %>
asdf
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<h1>Listing foods</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @foods.each do |food| %>
  <tr>
    <td><%= link_to food.name, food_path(food.id) %></td>
    <td>$<%= number_with_precision(food.price, :precision => 2) %></td>
    <td><%= link_to 'Show', food %></td>
    <td><%= link_to 'Edit', edit_food_path(food) %></td>
    <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>